version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-java
    tty: true
    working_dir: /app
    volumes:
      - .:/workspace
    ports:
      - 8080:8080 # 通常実行用
      - 5050:5050 # デバッグ用
      - 35729:35729 # LiveReload用
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:13
    container_name: demo-postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
